import { useEffect, useState } from 'react'
import { Card, CardContent } from '@/components/ui/card'; import { Badge } from '@/components/ui/badge'; import { Button } from '@/components/ui/button'
import { api } from '@/lib/api'; import type { RunSummary, RunDetail } from '@/types'
import { History, Download, CheckCircle, XCircle, ChevronDown, ChevronRight, Rocket, AlertTriangle, FileWarning } from 'lucide-react'
import { LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from 'recharts'
export default function HistoryPage() {
  const [data, setData] = useState<RunSummary[]>([]); const [expanded, setExpanded] = useState<string | null>(null); const [detail, setDetail] = useState<RunDetail | null>(null); const [loadingDetail, setLoadingDetail] = useState(false)
  useEffect(() => { api.history.list().then(setData).catch(() => {}) }, [])
  const downloadCsv = () => {
    const headers = ['run_id', 'src', 'dst', 'scanned', 'copied', 'failed', 'started_at', 'finished_at']
    const rows = data.map(r => headers.map(h => JSON.stringify((r as any)[h] ?? '')).join(','))
    const csv = [headers.join(','), ...rows].join('\n'); const blob = new Blob([csv], { type: 'text/csv' }); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = 'sync_history.csv'; a.click(); URL.revokeObjectURL(url)
  }
  const toggleExpand = async (runId: string) => { if (expanded === runId) { setExpanded(null); setDetail(null); return }; setExpanded(runId); setLoadingDetail(true); try { setDetail(await api.history.detail(runId)) } catch { setDetail(null) }; setLoadingDetail(false) }
  const useAsTemplate = (run: RunSummary) => { localStorage.setItem('active_tab', 'new-task'); if (run.config_json) { try { localStorage.setItem('template_config', run.config_json) } catch {} }; window.location.reload() }
  const downloadRunErrors = async (runId: string) => { try { const csv = await api.history.errorsCsv(runId); const blob = new Blob([csv], { type: 'text/csv' }); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = `errors_${runId}.csv`; a.click(); URL.revokeObjectURL(url) } catch {} }
  const chartData = data.filter(r => r.copied > 0).slice(-20).reverse().map((r, i) => ({ index: i + 1, copied: r.copied, elapsed: r.elapsed_ms ? Math.round(r.elapsed_ms / 1000) : 0 }))
  if (data.length === 0) return <Card><CardContent className="py-8 text-center text-zinc-500"><History className="w-8 h-8 mx-auto mb-2 opacity-50" />暂无历史记录</CardContent></Card>
  return <div className="space-y-6"><div className="flex items-center justify-between"><h2 className="text-lg font-bold flex items-center gap-2"><History className="w-5 h-5 text-indigo-400" />执行历史</h2><Button variant="outline" onClick={downloadCsv} className="gap-2"><Download className="w-4 h-4" />下载 CSV</Button></div>
    {chartData.length > 1 && <div className="rounded-2xl border border-white/[0.06] bg-white/[0.02] backdrop-blur-xl p-6"><p className="text-xs text-zinc-500 uppercase tracking-wider mb-4">同步趋势</p><div className="h-48"><ResponsiveContainer width="100%" height="100%"><LineChart data={chartData}><CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,0.04)" /><XAxis dataKey="index" tick={{ fill: '#71717a', fontSize: 11 }} tickLine={false} /><YAxis tick={{ fill: '#71717a', fontSize: 11 }} tickLine={false} /><Tooltip contentStyle={{ background: '#18181b', border: '1px solid rgba(255,255,255,0.08)', borderRadius: '8px', fontSize: '12px' }} /><Line type="monotone" dataKey="copied" stroke="#06f7f7" strokeWidth={2} dot={{ r: 3, fill: '#06f7f7' }} name="已复制" /><Line type="monotone" dataKey="elapsed" stroke="#a855f7" strokeWidth={2} dot={{ r: 3, fill: '#a855f7' }} name="耗时(秒)" /></LineChart></ResponsiveContainer></div></div>}
    <div className="overflow-x-auto rounded-2xl border border-white/[0.06] bg-white/[0.02] backdrop-blur-xl"><table className="glass-table w-full text-sm"><thead><tr><th className="w-8" /><th>源</th><th>目标</th><th className="text-right">已扫描</th><th className="text-right">已复制</th><th className="text-right">失败</th><th className="text-right">耗时</th><th className="text-left">时间</th><th className="text-left" /></tr></thead><tbody>
      {data.map(r => <><tr key={r.run_id} className="border-t border-white/[0.04] hover:bg-white/[0.03] transition-colors cursor-pointer" onClick={() => toggleExpand(r.run_id)}><td className="p-3">{expanded === r.run_id ? <ChevronDown className="w-4 h-4 text-zinc-500" /> : <ChevronRight className="w-4 h-4 text-zinc-500" />}</td><td className="max-w-[160px] truncate text-cyan-400">{r.src}</td><td className="max-w-[160px] truncate text-purple-400">{r.dst}</td><td className="text-right font-mono text-xs">{r.total_scanned.toLocaleString()}</td><td className="text-right font-mono text-xs text-emerald-400">{r.copied.toLocaleString()}</td><td className="text-right font-mono text-xs text-red-400">{r.failed}</td><td className="text-right font-mono text-xs">{r.elapsed_ms ? `${(r.elapsed_ms / 1000).toFixed(1)}s` : '-'}</td><td className="text-xs text-zinc-500">{r.started_at ? new Date(r.started_at).toLocaleString() : '-'}</td><td>{r.failed > 0 ? <XCircle className="w-4 h-4 text-red-400" /> : <CheckCircle className="w-4 h-4 text-emerald-400" />}</td></tr>
        {expanded === r.run_id && <tr key={`${r.run_id}-d`}><td colSpan={9} className="p-0"><div className="animate-[fade-in_0.2s_ease-out] bg-white/[0.02] border-t border-white/[0.04]"><div className="p-5 space-y-4">
          {loadingDetail ? <div className="flex items-center gap-2 text-zinc-500 text-sm"><div className="w-4 h-4 border-2 border-indigo-500 border-t-transparent rounded-full animate-spin" />加载中...</div>
          : detail ? <><div><p className="text-xs text-zinc-500 uppercase tracking-wider mb-2 flex items-center gap-1.5"><FileWarning className="w-3.5 h-3.5" />同步配置</p><div className="bg-black/30 rounded-xl p-4 font-mono text-xs space-y-1">
            {detail.run.config_json ? (() => { try { const cfg = JSON.parse(detail.run.config_json); return Object.entries(cfg).map(([k, v]) => <div key={k} className="flex gap-2"><span className="text-indigo-400 shrink-0">--{k.replace(/_/g, '-')}</span><span className="text-zinc-300">{typeof v === 'boolean' ? v ? 'true' : 'false' : Array.isArray(v) ? v.join(', ') : String(v)}</span></div>) } catch { return <span className="text-zinc-500">{detail.run.config_json}</span> }})()
            : <><div><span className="text-indigo-400">src</span><span className="text-zinc-300"> {detail.run.src}</span></div><div><span className="text-indigo-400">dst</span><span className="text-zinc-300"> {detail.run.dst}</span></div></>}
          </div></div>
          <div className="flex gap-2"><Button size="sm" className="gap-1.5" onClick={() => useAsTemplate(detail.run)}><Rocket className="w-3.5 h-3.5" />用此配置发起同步</Button>{(detail.errors.length > 0 || detail.run.failed > 0) && <Button variant="outline" size="sm" className="gap-1.5" onClick={() => downloadRunErrors(detail.run.run_id)}><AlertTriangle className="w-3.5 h-3.5 text-red-400" />下载报错 CSV ({detail.errors.length})</Button>}</div>
          {detail.errors.length > 0 && <div><p className="text-xs text-zinc-500 uppercase tracking-wider mb-2 flex items-center gap-1.5"><AlertTriangle className="w-3.5 h-3.5 text-red-400" />失败文件 ({detail.errors.length})</p><div className="overflow-x-auto rounded-lg border border-white/[0.06]"><table className="w-full text-xs"><thead><tr className="bg-red-500/5"><th className="text-left p-2 text-zinc-400 font-medium">源文件</th><th className="text-left p-2 text-zinc-400 font-medium">错误信息</th><th className="text-right p-2 text-zinc-400 font-medium">大小</th><th className="text-left p-2 text-zinc-400 font-medium">时间</th></tr></thead><tbody>{detail.errors.slice(0, 20).map((e, i) => <tr key={i} className="border-t border-white/[0.04]"><td className="p-2 max-w-[200px] truncate">{e.source_id}</td><td className="p-2 max-w-[300px] truncate text-red-400/80 font-mono">{e.error_message || '-'}</td><td className="p-2 text-right font-mono">{formatBytes(e.size)}</td><td className="p-2 text-zinc-500">{e.attempted_at ? new Date(e.attempted_at).toLocaleString() : '-'}</td></tr>)}</tbody></table></div></div>}
          </> : <p className="text-zinc-500 text-sm">无法加载详情</p>}
        </div></div></td></tr>}
      </>)}
    </tbody></table></div></div>
  function formatBytes(bytes: number): string { if (!bytes) return '0 B'; const units = ['B', 'KB', 'MB', 'GB', 'TB']; let i = 0, size = bytes; while (size >= 1024 && i < units.length - 1) { size /= 1024; i++ }; return `${size.toFixed(2)} ${units[i]}` }
}
