import { useEffect, useState } from 'react'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'; import { Input } from '@/components/ui/input'
import { Checkbox } from '@/components/ui/checkbox'; import { Slider } from '@/components/ui/slider'
import Terminal from '@/components/Terminal'; import { api } from '@/lib/api'
import { Rocket, Upload, Download, Sliders, FileWarning, Trash2, RefreshCw, Play } from 'lucide-react'
export default function NewTask() {
  const [src, setSrc] = useState(''); const [dst, setDst] = useState(''); const [threads, setThreads] = useState<number[]>([10])
  const [dryRun, setDryRun] = useState(false); const [deleteDst, setDeleteDst] = useState(false); const [update, setUpdate] = useState(false)
  const [result, setResult] = useState<{ command: string; message: string } | null>(null)
  useEffect(() => {
    const raw = localStorage.getItem('template_config')
    if (raw) { try { const cfg = JSON.parse(raw); if (cfg.src) setSrc(cfg.src); if (cfg.dst) setDst(cfg.dst); if (cfg.threads) setThreads([cfg.threads]); if (cfg.dry) setDryRun(true); if (cfg.delete_dst) setDeleteDst(true); if (cfg.update) setUpdate(true) } catch {}; localStorage.removeItem('template_config') }
  }, [])
  const handleSubmit = async () => { if (!src || !dst) return; try { setResult(await api.sync.start({ src, dst, threads: threads[0], dry_run: dryRun, delete_dst: deleteDst, update })) } catch (e) { console.error(e) } }
  return <div className="space-y-6 animate-[slide-up_0.3s_ease-out]"><Card className="tech-border"><CardHeader><CardTitle className="flex items-center gap-2"><Rocket className="w-5 h-5 text-indigo-400" />创建新的同步任务</CardTitle></CardHeader><CardContent className="space-y-6"><div className="grid grid-cols-1 md:grid-cols-2 gap-6"><div className="space-y-4"><div><p className="text-sm font-medium mb-2 flex items-center gap-1.5"><Upload className="w-4 h-4 text-cyan-400" />源存储</p><Input placeholder="s3://bucket/path 或 /local/path" value={src} onChange={e => setSrc(e.target.value)} /></div><div><p className="text-sm font-medium mb-2 flex items-center gap-1.5"><Download className="w-4 h-4 text-purple-400" />目标存储</p><Input placeholder="s3://bucket/path 或 /local/path" value={dst} onChange={e => setDst(e.target.value)} /></div></div><div className="space-y-4"><p className="text-sm font-medium mb-2 flex items-center gap-1.5"><Sliders className="w-4 h-4 text-pink-400" />高级选项</p><div className="space-y-2"><p className="text-xs text-zinc-500">并发线程数: {threads[0]}</p><Slider value={threads} onValueChange={v => setThreads(v as number[])} min={1} max={64} step={1} /></div><div className="flex items-center gap-2"><Checkbox id="dry" checked={dryRun} onCheckedChange={v => setDryRun(!!v)} /><label htmlFor="dry" className="text-sm flex items-center gap-1.5"><FileWarning className="w-3.5 h-3.5 text-amber-400" />Dry Run (模拟运行)</label></div><div className="flex items-center gap-2"><Checkbox id="delete" checked={deleteDst} onCheckedChange={v => setDeleteDst(!!v)} /><label htmlFor="delete" className="text-sm flex items-center gap-1.5"><Trash2 className="w-3.5 h-3.5 text-red-400" />删除目标端多余文件</label></div><div className="flex items-center gap-2"><Checkbox id="update" checked={update} onCheckedChange={v => setUpdate(!!v)} /><label htmlFor="update" className="text-sm flex items-center gap-1.5"><RefreshCw className="w-3.5 h-3.5 text-blue-400" />增量更新 (--update)</label></div></div></div><Button onClick={handleSubmit} className="w-full gap-2" disabled={!src || !dst}><Play className="w-4 h-4" />开始同步</Button>{result && <div className="space-y-3"><p className="text-sm text-zinc-500">{result.message}</p><Terminal>{result.command}</Terminal></div>}</CardContent></Card></div>
}
