import { useEffect, useState } from 'react'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'; import { Badge } from '@/components/ui/badge'; import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'; import { Slider } from '@/components/ui/slider'
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { api } from '@/lib/api'; import type { ScheduleTask, ScheduleHistory } from '@/types'
import { Clock, Plus, History, Play, Pause, Trash2, Save, Upload, Download } from 'lucide-react'
const CRON_MAP: Record<string, string> = { '每小时': '0 * * * *', '每天凌晨2点': '0 2 * * *', '每天中午12点': '0 12 * * *', '每周一': '0 9 * * 1', '每月1号': '0 0 1 * *' }
export default function Schedule() {
  const [tasks, setTasks] = useState<ScheduleTask[]>([]); const [open, setOpen] = useState(false)
  const [name, setName] = useState(''); const [src, setSrc] = useState(''); const [dst, setDst] = useState(''); const [preset, setPreset] = useState('自定义'); const [cronExpr, setCronExpr] = useState('0 2 * * *'); const [threads, setThreads] = useState<number[]>([10])
  const [historyData, setHistoryData] = useState<ScheduleHistory[] | null>(null); const [historyOpen, setHistoryOpen] = useState(false)
  const load = async () => { try { setTasks(await api.schedules.list()) } catch {} }
  useEffect(() => { load() }, [])
  const handleCreate = async () => { if (!name || !src || !dst || !cronExpr) return; try { await api.schedules.create({ name, src, dst, cron_expr: cronExpr, enabled: true, threads: threads[0], options: '{}' }); setOpen(false); setName(''); setSrc(''); setDst(''); setCronExpr('0 2 * * *'); setPreset('自定义'); setThreads([10]); await load() } catch (e) { console.error(e) } }
  const handleToggle = async (task: ScheduleTask) => { try { await api.schedules.update(task.id, { enabled: !task.enabled }); await load() } catch (e) { console.error(e) } }
  const handleDelete = async (id: number) => { try { await api.schedules.delete(id); await load() } catch (e) { console.error(e) } }
  const handleShowHistory = async (taskId: number) => { try { setHistoryData(await api.schedules.history(taskId)); setHistoryOpen(true) } catch {} }
  const handlePresetChange = (v: string | null) => { if (!v) return; setPreset(v); if (v !== '自定义' && CRON_MAP[v]) setCronExpr(CRON_MAP[v]) }
  return <div className="space-y-6 animate-[slide-up_0.3s_ease-out]"><div className="flex items-center justify-between"><h2 className="text-lg font-bold flex items-center gap-2"><Clock className="w-5 h-5 text-indigo-400" />调度管理</h2><Dialog open={open} onOpenChange={setOpen}><DialogTrigger><Button className="gap-2"><Plus className="w-4 h-4" />创建调度</Button></DialogTrigger><DialogContent className="max-w-lg"><DialogHeader><DialogTitle>创建新调度任务</DialogTitle></DialogHeader><div className="space-y-4 py-4"><Input placeholder="任务名称" value={name} onChange={e => setName(e.target.value)} /><Input placeholder="源路径" value={src} onChange={e => setSrc(e.target.value)} /><Input placeholder="目标路径" value={dst} onChange={e => setDst(e.target.value)} /><Select value={preset} onValueChange={handlePresetChange}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="自定义">自定义</SelectItem><SelectItem value="每小时">每小时</SelectItem><SelectItem value="每天凌晨2点">每天凌晨2点</SelectItem><SelectItem value="每天中午12点">每天中午12点</SelectItem><SelectItem value="每周一">每周一</SelectItem><SelectItem value="每月1号">每月1号</SelectItem></SelectContent></Select>{preset === '自定义' && <Input placeholder="Cron 表达式" value={cronExpr} onChange={e => setCronExpr(e.target.value)} />}<Badge variant="outline" className="font-mono">{cronExpr}</Badge><div className="space-y-2"><p className="text-sm">并发线程数: {threads[0]}</p><Slider value={threads} onValueChange={v => setThreads(v as number[])} min={1} max={64} step={1} /></div><Button onClick={handleCreate} className="w-full gap-2"><Save className="w-4 h-4" />保存</Button></div></DialogContent></Dialog></div>
    {tasks.length === 0 ? <Card><CardContent className="py-8 text-center text-zinc-500"><Clock className="w-8 h-8 mx-auto mb-2 opacity-50" />暂无调度任务，创建一个吧!</CardContent></Card>
    : <div className="grid grid-cols-1 md:grid-cols-2 gap-4">{tasks.map(t => <Card key={t.id} className="tech-border"><CardContent className="pt-6 space-y-3"><div className="flex items-start justify-between"><div><p className="font-semibold">{t.name}</p><p className="text-sm text-zinc-500 mt-1"><span className="text-cyan-400">{t.src}</span><span className="mx-2 text-zinc-600">→</span><span className="text-purple-400">{t.dst}</span></p></div><Badge variant={t.enabled ? 'default' : 'secondary'}>{t.enabled ? '已启用' : '已禁用'}</Badge></div><div className="flex items-center gap-3 text-xs text-zinc-500"><span className="font-mono text-pink-400 bg-pink-500/10 px-2 py-1 rounded">{t.cron_expr}</span>{t.next_run && <span>下次: {new Date(t.next_run).toLocaleString()}</span>}</div><div className="flex gap-2"><Button variant="outline" size="sm" onClick={() => handleShowHistory(t.id)} className="gap-1.5"><History className="w-3.5 h-3.5" />历史</Button><Button variant="outline" size="sm" onClick={() => handleToggle(t)} className="gap-1.5">{t.enabled ? <><Pause className="w-3.5 h-3.5" /> 禁用</> : <><Play className="w-3.5 h-3.5" /> 启用</>}</Button><Button variant="destructive" size="sm" onClick={() => handleDelete(t.id)} className="gap-1.5"><Trash2 className="w-3.5 h-3.5" />删除</Button></div></CardContent></Card>)}</div>}
    <Dialog open={historyOpen} onOpenChange={setHistoryOpen}><DialogContent className="max-w-3xl max-h-[80vh] overflow-y-auto"><DialogHeader><DialogTitle>执行历史</DialogTitle></DialogHeader>
      {historyData && historyData.length > 0 ? <table className="glass-table w-full text-sm"><thead><tr><th className="text-left">开始时间</th><th className="text-left">状态</th><th className="text-right">复制数</th></tr></thead><tbody>{historyData.map(h => <tr key={h.id} className="border-t border-white/[0.04]"><td className="text-xs text-zinc-500">{new Date(h.started_at).toLocaleString()}</td><td><Badge variant={h.status === 'success' ? 'default' : h.status === 'timeout' ? 'secondary' : 'destructive'}>{h.status === 'success' ? '成功' : h.status === 'timeout' ? '超时' : h.status === 'failed' ? '失败' : h.status}</Badge></td><td className="text-right font-mono text-xs">{h.objects_copied}</td></tr>)}</tbody></table> : <p className="text-zinc-500 text-center py-8">暂无执行记录</p>}
    </DialogContent></Dialog></div>
}
