import { useEffect, useState } from 'react'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'; import { Button } from '@/components/ui/button'; import { Input } from '@/components/ui/input'
import { Textarea } from '@/components/ui/textarea'; import { Slider } from '@/components/ui/slider'
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog'
import { api } from '@/lib/api'; import type { Template } from '@/types'
import { FileText, Plus, Save, Trash2, Play, Sliders, Sparkles } from 'lucide-react'
function expandTemplate(t: string): string {
  const now = new Date(); const pad = (n: number) => n.toString().padStart(2, '0')
  return t.replace(/\{date\}/g, `${now.getFullYear()}${pad(now.getMonth()+1)}${pad(now.getDate())}`).replace(/\{datetime\}/g, `${now.getFullYear()}${pad(now.getMonth()+1)}${pad(now.getDate())}${pad(now.getHours())}${pad(now.getMinutes())}${pad(now.getSeconds())}`).replace(/\{yyyy\}/g, now.getFullYear().toString()).replace(/\{mm\}/g, pad(now.getMonth()+1)).replace(/\{dd\}/g, pad(now.getDate())).replace(/\{HH\}/g, pad(now.getHours())).replace(/\{MM\}/g, pad(now.getMinutes())).replace(/\{SS\}/g, pad(now.getSeconds()))
}
export default function Templates() {
  const [templates, setTemplates] = useState<Template[]>([]); const [open, setOpen] = useState(false)
  const [name, setName] = useState(''); const [desc, setDesc] = useState(''); const [srcTmpl, setSrcTmpl] = useState(''); const [dstTmpl, setDstTmpl] = useState(''); const [threads, setThreads] = useState<number[]>([10])
  const load = async () => { try { setTemplates(await api.templates.list()) } catch {} }
  useEffect(() => { load() }, [])
  const handleCreate = async () => { if (!name || !srcTmpl || !dstTmpl) return; try { await api.templates.create({ name, description: desc, src_template: srcTmpl, dst_template: dstTmpl, threads: threads[0], options: '{}' }); setOpen(false); setName(''); setDesc(''); setSrcTmpl(''); setDstTmpl(''); setThreads([10]); await load() } catch (e) { console.error(e) } }
  const handleDelete = async (id: number) => { try { await api.templates.delete(id); await load() } catch (e) { console.error(e) } }
  return <div className="space-y-6 animate-[slide-up_0.3s_ease-out]"><div className="flex items-center justify-between"><h2 className="text-lg font-bold flex items-center gap-2"><FileText className="w-5 h-5 text-indigo-400" />配置模板</h2><Dialog open={open} onOpenChange={setOpen}><DialogTrigger><Button className="gap-2"><Plus className="w-4 h-4" />创建模板</Button></DialogTrigger><DialogContent className="max-w-2xl"><DialogHeader><DialogTitle>创建新模板</DialogTitle></DialogHeader><div className="space-y-4 py-4"><Input placeholder="模板名称" value={name} onChange={e => setName(e.target.value)} /><Textarea placeholder="模板描述" value={desc} onChange={e => setDesc(e.target.value)} /><p className="text-xs text-zinc-500 flex items-center gap-1"><Sparkles className="w-3 h-3" />支持变量: {'{date}'}, {'{yyyy}'}, {'{mm}'}, {'{dd}'}, {'{HH}'}, {'{MM}'}, {'{SS}'}</p><Input placeholder="源路径模板" value={srcTmpl} onChange={e => setSrcTmpl(e.target.value)} /><Input placeholder="目标路径模板" value={dstTmpl} onChange={e => setDstTmpl(e.target.value)} /><div className="space-y-2"><p className="text-sm flex items-center gap-1.5"><Sliders className="w-3.5 h-3.5 text-pink-400" />并发线程数: {threads[0]}</p><Slider value={threads} onValueChange={v => setThreads(v as number[])} min={1} max={64} step={1} /></div>{(srcTmpl || dstTmpl) && <Card className="bg-white/[0.03] border-white/[0.06]"><CardContent className="pt-4 space-y-1 text-sm"><p className="text-xs text-zinc-500 mb-2">预览:</p>{srcTmpl && <p>源: <code className="text-cyan-400">{expandTemplate(srcTmpl)}</code></p>}{dstTmpl && <p>目标: <code className="text-cyan-400">{expandTemplate(dstTmpl)}</code></p>}</CardContent></Card>}<Button onClick={handleCreate} className="w-full gap-2"><Save className="w-4 h-4" />保存</Button></div></DialogContent></Dialog></div>
    {templates.length === 0 ? <Card><CardContent className="py-8 text-center text-zinc-500"><FileText className="w-8 h-8 mx-auto mb-2 opacity-50" />暂无模板，创建一个吧!</CardContent></Card>
    : <div className="grid grid-cols-1 md:grid-cols-2 gap-4">{templates.map(t => <Card key={t.id} className="tech-border"><CardContent className="pt-6 space-y-3"><div className="flex items-start justify-between"><div><p className="font-semibold">{t.name}</p><p className="text-xs text-zinc-500">{t.description || '无描述'}</p></div><span className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-purple-500/20 text-purple-400 border border-purple-500/30"><Sliders className="w-3 h-3 mr-1" />{t.threads} 线程</span></div><div className="text-sm space-y-1 text-zinc-500"><p><span className="text-cyan-400">源:</span> {t.src_template}</p><p><span className="text-purple-400">目标:</span> {t.dst_template}</p></div><div className="flex gap-2"><Button variant="outline" size="sm" className="flex-1 gap-1.5"><Play className="w-3.5 h-3.5" />应用</Button><Button variant="destructive" size="sm" onClick={() => handleDelete(t.id)} className="gap-1.5"><Trash2 className="w-3.5 h-3.5" />删除</Button></div></CardContent></Card>)}</div>}
}
